name: Siguldas Skati Tests

on:
  push:
    branches: [ "staging", "master" ]
  pull_request:
    branches: [ "staging", "master" ]

jobs:
  php-8-3-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.3'
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs
      - name: Install NPM
        run: npm install
      - name: Build Assets
        run: npm run build
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Storage Link
        run: php artisan storage:link
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Migrate Database
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan migrate --force
      - name: Execute tests (Unit and Feature tests) via Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test


  deploy-staging:
    needs: php-8-3-tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    environment: staging

    steps:
      - name: Deploy to Staging
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://forge.laravel.com/api/v1/servers/${{ secrets.FORGE_STAGING_SERVER_ID }}/sites/${{ secrets.FORGE_STAGING_SITE_ID }}/deployment/deploy'
          method: 'POST'
          customHeaders: '{"Authorization": "Bearer ${{ secrets.FORGE_API_TOKEN }}", "Accept": "application/json", "Content-Type": "application/json"}'

  deploy-production:
    needs: php-8-3-tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    environment: production

    steps:
      - name: Deploy to Production
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://forge.laravel.com/api/v1/servers/${{ secrets.FORGE_PRODUCTION_SERVER_ID }}/sites/${{ secrets.FORGE_PRODUCTION_SITE_ID }}/deployment/deploy'
          method: 'POST'
          customHeaders: '{"Authorization": "Bearer ${{ secrets.FORGE_API_TOKEN }}", "Accept": "application/json", "Content-Type": "application/json"}'
